// =============================================================================
// @migrare/lovable — LovablePlugin (reference implementation)
//
// The first production plugin and canonical example of IPlugin.
// Targets projects generated by Lovable (lovable.dev).
//
// DETECTION FINGERPRINT (any → high confidence):
//   - 'lovable-tagger' in devDependencies
//   - GPT_ENGINEER_* or LOVABLE_* env vars
//   - src/integrations/supabase/client.ts exists
//   - @supabase/supabase-js in dependencies
//
// LOCK-IN VECTORS + TRANSFORMS:
//   build-config       lovable-tagger in vite.config  → RemoveLovableTaggerTransform
//   state-entanglement hardcoded Supabase credentials  → AbstractSupabaseClientTransform
//   environment-bleed  GPT_ENGINEER_* env vars         → RemoveEnvBleedTransform
//   auth-coupling      direct @supabase/* imports      → flagged for manual review
//
// TRANSFORM ORDER: build config → credential abstraction → env var rename.
// Clean the build config before touching env vars to avoid false positives.
//
// VALIDATORS:
//   pre-scan:    confirms @supabase/supabase-js present (expected dependency)
//   post-migrate: asserts lovable-tagger is removed from package.json
//
// Lovable lock-in vectors:
//   1. @supabase/* imported directly in components (auth-coupling)
//   2. lovable-tagger dev dependency + componentTagger() in vite.config (build-config)
//   3. GPT_ENGINEER_* env vars / __lovable_* globals (environment-bleed)
//   4. Hardcoded Supabase project URLs in source (proprietary-api)
//   5. src/integrations/supabase/ generated client folder (state-entanglement)
//   6. toast() from @/hooks/use-toast wrapping Sonner/Radix (state-entanglement)
// =============================================================================

import type {
  IPlugin,
  PluginMeta,
  IScanner,
  ITransform,
  IValidator,
  DetectionResult,
  LockInSignal,
  ScanContext,
  TransformContext,
  TransformResult,
  ValidationResult,
  ValidationContext,
  MigrareEngine,
  LockInCategory,
  ProjectFile,
} from "../../core/types/index.js";
import type { ProjectGraph } from "../../core/ProjectGraph.js";

// ---------------------------------------------------------------------------
// Detection
// ---------------------------------------------------------------------------

async function detectLovable(graph: ProjectGraph): Promise<DetectionResult> {
  const signals: string[] = [];

  // Strong signals
  if (graph.hasDependency("lovable-tagger")) signals.push("lovable-tagger dependency");
  if (graph.getFile("src/integrations/supabase/client.ts")) signals.push("generated supabase client");
  if (graph.getFile(".lovable")) signals.push(".lovable config file");

  // Medium signals
  const viteConfig = graph.getFile("vite.config.ts") ?? graph.getFile("vite.config.js");
  if (viteConfig?.content.includes("componentTagger")) signals.push("componentTagger in vite.config");

  const pkg = graph.getFile("package.json");
  if (pkg?.content.includes("lovable")) signals.push("lovable in package.json");

  // Env bleed
  const envFile = graph.getFile(".env") ?? graph.getFile(".env.local");
  if (envFile?.content.includes("GPT_ENGINEER")) signals.push("GPT_ENGINEER env var");

  const detected = signals.length >= 1;
  const confidence =
    signals.length >= 3 ? "high" : signals.length >= 1 ? "medium" : "low";

  return { detected, confidence, signals };
}

// ---------------------------------------------------------------------------
// Scanners
// ---------------------------------------------------------------------------

class SupabaseDirectImportScanner implements IScanner {
  readonly id = "lovable.supabase-direct-import";
  readonly category: LockInCategory = "auth-coupling";
  readonly description = "Detects direct @supabase/* imports in component files";

  async scan(graph: ProjectGraph, ctx: ScanContext): Promise<LockInSignal[]> {
    const signals: LockInSignal[] = [];
    const supabaseImport = /@supabase\/(supabase-js|auth-helpers|ssr)/;

    for (const file of graph.findFiles(/\.(tsx?|jsx?)$/)) {
      const lines = file.content.split("\n");
      lines.forEach((line, i) => {
        if (supabaseImport.test(line)) {
          signals.push({
            id: `${this.id}:${file.path}:${i}`,
            platform: ctx.platform,
            category: this.category,
            severity: "warning",
            confidence: "high",
            location: { file: file.path, line: i + 1 },
            description: `Direct Supabase import in component — will break outside Lovable environment`,
            suggestion: `Extract to a service layer: src/services/auth.ts`,
            meta: { line: line.trim() },
          });
        }
      });
    }
    return signals;
  }
}

class LovableBuildConfigScanner implements IScanner {
  readonly id = "lovable.build-config";
  readonly category: LockInCategory = "build-config";
  readonly description = "Detects lovable-tagger and componentTagger in vite.config";

  async scan(graph: ProjectGraph, ctx: ScanContext): Promise<LockInSignal[]> {
    const signals: LockInSignal[] = [];
    const viteConfig = graph.getFile("vite.config.ts") ?? graph.getFile("vite.config.js");

    if (viteConfig?.content.includes("lovable-tagger")) {
      signals.push({
        id: `${this.id}:vite-config`,
        platform: ctx.platform,
        category: this.category,
        severity: "warning",
        confidence: "high",
        location: { file: viteConfig.path },
        description: `lovable-tagger plugin in vite.config is a Lovable-only dev tool`,
        suggestion: `Remove componentTagger() from plugins array`,
        meta: {},
      });
    }

    if (graph.hasDependency("lovable-tagger")) {
      signals.push({
        id: `${this.id}:package-json`,
        platform: ctx.platform,
        category: this.category,
        severity: "info",
        confidence: "high",
        location: { file: "package.json" },
        description: `lovable-tagger in devDependencies serves no purpose outside Lovable`,
        suggestion: `Remove from devDependencies`,
        meta: {},
      });
    }

    return signals;
  }
}

class GeneratedSupabaseClientScanner implements IScanner {
  readonly id = "lovable.generated-supabase-client";
  readonly category: LockInCategory = "state-entanglement";
  readonly description = "Detects the auto-generated Supabase client folder";

  async scan(graph: ProjectGraph, ctx: ScanContext): Promise<LockInSignal[]> {
    const signals: LockInSignal[] = [];
    const clientFile = graph.getFile("src/integrations/supabase/client.ts");
    const typesFile = graph.getFile("src/integrations/supabase/types.ts");

    if (clientFile) {
      signals.push({
        id: `${this.id}:client`,
        platform: ctx.platform,
        category: this.category,
        severity: "error",
        confidence: "high",
        location: { file: clientFile.path },
        description: `Generated Supabase client contains hardcoded project URL and anon key`,
        suggestion: `Move credentials to .env and create a portable client factory`,
        meta: {},
      });
    }

    if (typesFile) {
      signals.push({
        id: `${this.id}:types`,
        platform: ctx.platform,
        category: this.category,
        severity: "info",
        confidence: "high",
        location: { file: typesFile.path },
        description: `Generated Supabase types can be regenerated via supabase CLI — not a blocker`,
        suggestion: `Run: supabase gen types typescript --project-id <id>`,
        meta: {},
      });
    }

    return signals;
  }
}

class EnvBleedScanner implements IScanner {
  readonly id = "lovable.env-bleed";
  readonly category: LockInCategory = "environment-bleed";
  readonly description = "Detects Lovable-specific env vars and globals";

  async scan(graph: ProjectGraph, ctx: ScanContext): Promise<LockInSignal[]> {
    const signals: LockInSignal[] = [];
    const lovableEnvPattern = /GPT_ENGINEER_|LOVABLE_|__lovable/;

    for (const file of graph.findFiles(/(\.env|\.ts|\.tsx|\.js|\.jsx)$/)) {
      const lines = file.content.split("\n");
      lines.forEach((line, i) => {
        if (lovableEnvPattern.test(line)) {
          signals.push({
            id: `${this.id}:${file.path}:${i}`,
            platform: ctx.platform,
            category: this.category,
            severity: "warning",
            confidence: "medium",
            location: { file: file.path, line: i + 1 },
            description: `Lovable-specific env var or global: ${line.trim()}`,
            suggestion: `Replace with standard VITE_* env var`,
            meta: { line: line.trim() },
          });
        }
      });
    }

    return signals;
  }
}

// ---------------------------------------------------------------------------
// Transforms
// ---------------------------------------------------------------------------

class RemoveLovableTaggerTransform implements ITransform {
  readonly id = "lovable.remove-tagger";
  readonly description = "Removes lovable-tagger from vite.config and package.json";
  readonly category: LockInCategory = "build-config";
  readonly platforms = ["lovable"];

  appliesTo(graph: ProjectGraph): boolean {
    return (
      graph.hasDependency("lovable-tagger") ||
      !!(graph.getFile("vite.config.ts") ?? graph.getFile("vite.config.js"))?.content.includes("lovable-tagger")
    );
  }

  async apply(graph: ProjectGraph, ctx: TransformContext): Promise<TransformResult> {
    const modified: string[] = [];

    // Remove from vite.config
    const viteConfig = graph.getFile("vite.config.ts") ?? graph.getFile("vite.config.js");
    if (viteConfig) {
      let content = viteConfig.content;
      // Remove import line
      content = content.replace(/^.*import.*lovable-tagger.*\n/m, "");
      // Remove componentTagger() call (handles trailing comma)
      content = content.replace(/\s*componentTagger\(\),?\s*/g, "");
      // Clean up empty plugin arrays
      content = content.replace(/plugins:\s*\[\s*\]/g, "plugins: []");
      viteConfig.content = content;
      viteConfig.modified = true;
      modified.push(viteConfig.path);
      ctx.logger.info(`Removed lovable-tagger from ${viteConfig.path}`);
    }

    // Remove from package.json
    const pkgFile = graph.getFile("package.json");
    if (pkgFile) {
      try {
        const pkg = JSON.parse(pkgFile.content);
        if (pkg.devDependencies?.["lovable-tagger"]) {
          delete pkg.devDependencies["lovable-tagger"];
          pkgFile.content = JSON.stringify(pkg, null, 2);
          pkgFile.modified = true;
          modified.push(pkgFile.path);
          ctx.logger.info(`Removed lovable-tagger from package.json`);
        }
      } catch {
        ctx.logger.warn(`Could not parse package.json`);
      }
    }

    return { modified, created: [], deleted: [], warnings: [], meta: {} };
  }
}

class AbstractSupabaseClientTransform implements ITransform {
  readonly id = "lovable.abstract-supabase-client";
  readonly description = "Moves Supabase credentials to env vars and creates a portable client factory";
  readonly category: LockInCategory = "state-entanglement";
  readonly platforms = ["lovable"];

  appliesTo(graph: ProjectGraph): boolean {
    return !!graph.getFile("src/integrations/supabase/client.ts");
  }

  async apply(graph: ProjectGraph, ctx: TransformContext): Promise<TransformResult> {
    const modified: string[] = [];
    const created: string[] = [];
    const clientFile = graph.getFile("src/integrations/supabase/client.ts");
    if (!clientFile) return { modified, created, deleted: [], warnings: [], meta: {} };

    // Extract hardcoded URL and key
    const urlMatch = clientFile.content.match(/["'](https:\/\/[a-zA-Z0-9]+\.supabase\.co)["']/);
    const keyMatch = clientFile.content.match(/["']([a-zA-Z0-9._-]{100,})["']/);

    const url = urlMatch?.[1] ?? "YOUR_SUPABASE_URL";
    const key = keyMatch?.[1] ?? "YOUR_SUPABASE_ANON_KEY";

    // Create portable client
    const portableClient = `// Generated by migrare — Lovable migration
// Supabase client using environment variables instead of hardcoded values.
import { createClient } from "@supabase/supabase-js";

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error(
    "Missing Supabase env vars. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in .env"
  );
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);
`;

    clientFile.content = portableClient;
    clientFile.modified = true;
    modified.push(clientFile.path);

    // Create or update .env.example
    const envExample = graph.getFile(".env.example");
    const envLines = `# Supabase — extracted by migrare from Lovable project\nVITE_SUPABASE_URL=${url}\nVITE_SUPABASE_ANON_KEY=<your-anon-key>\n`;

    if (envExample) {
      if (!envExample.content.includes("VITE_SUPABASE_URL")) {
        envExample.content += `\n${envLines}`;
        envExample.modified = true;
        modified.push(".env.example");
      }
    } else {
      graph.addFile({
        path: ".env.example",
        content: envLines,
        encoding: "utf8",
        modified: false,
        meta: { generatedBy: "migrare:lovable.abstract-supabase-client" },
      });
      created.push(".env.example");
    }

    ctx.logger.info(`Abstracted Supabase client`, { url, keyLength: key.length });
    ctx.logger.warn(`Original URL extracted for .env.example — do NOT commit actual keys`);

    return { modified, created, deleted: [], warnings: [], meta: { extractedUrl: url } };
  }
}

class RemoveEnvBleedTransform implements ITransform {
  readonly id = "lovable.remove-env-bleed";
  readonly description = "Replaces Lovable-specific env vars with standard VITE_* equivalents";
  readonly category: LockInCategory = "environment-bleed";
  readonly platforms = ["lovable"];

  appliesTo(graph: ProjectGraph): boolean {
    return graph
      .findFiles(/\.(env|ts|tsx|js|jsx)$/)
      .some((f) => /GPT_ENGINEER_|LOVABLE_/.test(f.content));
  }

  async apply(graph: ProjectGraph, ctx: TransformContext): Promise<TransformResult> {
    const modified: string[] = [];

    for (const file of graph.findFiles(/\.(env|ts|tsx|js|jsx)$/)) {
      if (!/GPT_ENGINEER_|LOVABLE_/.test(file.content)) continue;

      let content = file.content;
      content = content.replace(/GPT_ENGINEER_/g, "VITE_");
      content = content.replace(/LOVABLE_/g, "VITE_");
      content = content.replace(/import\.meta\.env\.VITE_VITE_/g, "import.meta.env.VITE_"); // fix double-prefix

      file.content = content;
      file.modified = true;
      modified.push(file.path);
      ctx.logger.info(`Cleaned env bleed from ${file.path}`);
    }

    return { modified, created: [], deleted: [], warnings: [], meta: {} };
  }
}

// ---------------------------------------------------------------------------
// Validators
// ---------------------------------------------------------------------------

class SupabaseDepsValidator implements IValidator {
  readonly id = "lovable.validate-supabase-deps";
  readonly phase = "pre-transform" as const;
  readonly description = "Ensures @supabase/supabase-js is present before transform";

  async validate(graph: ProjectGraph, _ctx: ValidationContext): Promise<ValidationResult> {
    const hasSupabase = graph.hasDependency("@supabase/supabase-js");
    return {
      phase: this.phase,
      passed: true, // non-blocking — just inform
      issues: hasSupabase
        ? []
        : [
            {
              code: "SUPABASE_DEP_MISSING",
              message: `@supabase/supabase-js not found. Supabase transforms will be skipped.`,
              severity: "info",
            },
          ],
    };
  }
}

class PostMigrateStructureValidator implements IValidator {
  readonly id = "lovable.validate-post-structure";
  readonly phase = "post-transform" as const;
  readonly description = "Checks that critical files remain after transforms";

  async validate(graph: ProjectGraph, _ctx: ValidationContext): Promise<ValidationResult> {
    const issues: import("../../core/types/index.js").MigrareIssue[] = [];

    const requiredFiles = ["package.json", "vite.config.ts", "src/main.tsx", "index.html"];
    for (const path of requiredFiles) {
      if (!graph.getFile(path)) {
        issues.push({
          code: "MISSING_REQUIRED_FILE",
          message: `Required file missing after transforms: ${path}`,
          severity: "error",
          location: { file: path },
        });
      }
    }

    // Ensure no lovable-tagger remains
    const viteConfig = graph.getFile("vite.config.ts") ?? graph.getFile("vite.config.js");
    if (viteConfig?.content.includes("lovable-tagger")) {
      issues.push({
        code: "LOVABLE_TAGGER_REMAINS",
        message: `lovable-tagger still present in vite.config after transform`,
        severity: "warning",
        location: { file: viteConfig.path },
      });
    }

    return {
      phase: this.phase,
      passed: issues.filter((i) => i.severity === "error").length === 0,
      issues,
    };
  }
}

// ---------------------------------------------------------------------------
// Plugin assembly
// ---------------------------------------------------------------------------

export class LovablePlugin implements IPlugin {
  readonly meta: PluginMeta = {
    id: "lovable",
    name: "Lovable",
    version: "1.0.0",
    description: "Migration support for projects built on lovable.dev",
    homepage: "https://lovable.dev",
  };

  async onRegister(engine: MigrareEngine): Promise<void> {
    engine.logger.info(`Lovable plugin ready`, { version: this.meta.version });
  }

  async detect(graph: ProjectGraph): Promise<DetectionResult> {
    return detectLovable(graph);
  }

  getScanners(): IScanner[] {
    return [
      new SupabaseDirectImportScanner(),
      new LovableBuildConfigScanner(),
      new GeneratedSupabaseClientScanner(),
      new EnvBleedScanner(),
    ];
  }

  getTransforms(): ITransform[] {
    return [
      new RemoveLovableTaggerTransform(),
      new AbstractSupabaseClientTransform(),
      new RemoveEnvBleedTransform(),
    ];
  }

  getValidators(): IValidator[] {
    return [
      new SupabaseDepsValidator(),
      new PostMigrateStructureValidator(),
    ];
  }

  hooks = {
    "before:scan": async (graph: ProjectGraph) => {
      // Could log Lovable-specific pre-scan info
    },
    "after:scan": async (graph: ProjectGraph, report: import("../../core/types/index.js").ScanReport) => {
      if (report.summary.migrationComplexity === "requires-manual") {
        console.warn(
          `[lovable] This project has manual migration requirements. Review the scan report before proceeding.`
        );
      }
    },
  };
}

